language: node_js
node_js:
  - '8'
addons:
  ssh_known_hosts: manual.os-js.org
cache: npm
install:
  - npm install -g gitbook gitbook-cli
  - npm install
script:
  - gitbook build
  - node index.js
  - mkdir dist
  - cp public/*.* dist/
  - cp -r _metalsmith dist/v2
  - cp -r _book dist/v3
  - echo "$GA_CONTENTS" > "dist/${GA_FILENAME}"
  - echo "$GA_CONTENTS" > "dist/v2/${GA_FILENAME}"
  - echo "$GA_CONTENTS" > "dist/v2/${GA_FILENAME}"
before_deploy:
  - openssl aes-256-cbc -K $encrypted_97cfa6c435f9_key -iv $encrypted_97cfa6c435f9_iv
    -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/dist/* anders@manual.os-js.org:manual/travis/
  on:
    branch: master
